FROM ubuntu

ARG FMT_VERSION=5.1.0

RUN apt update && \
    apt install -y build-essential git ninja-build curl cmake lcov gcovr pkg-config \
                   libgit2-dev googletest unzip \
                   clang-format-3.9 yapf3 python3-pkg-resources \
 && rm -rf /var/lib/apt/lists/*

RUN curl -L -O https://github.com/fmtlib/fmt/releases/download/${FMT_VERSION}/fmt-${FMT_VERSION}.zip \
 && unzip fmt-${FMT_VERSION}.zip \
 && mkdir fmt-${FMT_VERSION}/build \
 && cd fmt-${FMT_VERSION}/build \
 && cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=17 -DBUILD_SHARED_LIBS=YES -GNinja .. \
 && cmake --build . --target install \
 && cd ../.. && rm -rf fmt-${FMT_VERSION}.zip fmt-${FMT_VERSION}
