FROM ubuntu

RUN apt update && \
    apt install -y build-essential git ninja-build curl cmake lcov gcovr pkg-config \
                   libgit2-dev googletest \
                   clang-format-3.9 yapf3 python3-pkg-resources \
 && rm -rf /var/lib/apt/lists/*
