###############################################################################
# (c) Copyright 2018 CERN for the benefit of the LHCb Collaboration           #
#                                                                             #
# This software is distributed under the terms of the Apache version 2        #
# licence, copied verbatim in the file "COPYING".                             #
#                                                                             #
# In applying this licence, CERN does not waive the privileges and immunities #
# granted to it by virtue of its status as an Intergovernmental Organization  #
# or submit itself to any jurisdiction.                                       #
###############################################################################

stages:
  - images
  - build
  - test

variables:
  BUILDDIR: build

ubuntu-image:
  stage: images
  tags:
    - docker-image-build
  only:
    - docker-images
  script: "echo" # unused but this line is required by GitLab CI
  variables:
    TO: ${CI_REGISTRY_IMAGE}:ubuntu
    DOCKER_FILE: tests/docker/Dockerfile-ubuntu


build-ubuntu-rel:
  stage: build
  image: gitlab-registry.cern.ch/lhcb/gitconddb:ubuntu
  script:
    - mkdir -p ${BUILDDIR}
    - cd ${BUILDDIR}
    - cmake -GNinja -DCMAKE_BUILD_TYPE=Release ..
    - cmake --build . --target all
  artifacts:
    paths:
      - ${BUILDDIR}

test-ubuntu-rel:
  stage: test
  image: gitlab-registry.cern.ch/lhcb/gitconddb:ubuntu
  dependencies: [build-ubuntu-rel]
  script:
    - find ${BUILDDIR} -type f -exec touch -d $(date +@%s) \{} \;
    - cmake --build ${BUILDDIR} --target test


build-ubuntu-cov:
  stage: build
  image: gitlab-registry.cern.ch/lhcb/gitconddb:ubuntu
  script:
    - mkdir -p ${BUILDDIR}
    - cd ${BUILDDIR}
    - cmake -GNinja -DCMAKE_BUILD_TYPE=Coverage ..
    - cmake --build . --target all
  artifacts:
    paths:
      - ${BUILDDIR}

test-ubuntu-cov:
  stage: test
  image: gitlab-registry.cern.ch/lhcb/gitconddb:ubuntu
  dependencies: [build-ubuntu-cov]
  script:
    - find ${BUILDDIR} -type f -exec touch -d $(date +@%s) \{} \;
    - cmake --build ${BUILDDIR} --target clean-coverage-stats
    - cmake --build ${BUILDDIR} --target test
    - cmake --build ${BUILDDIR} --target generate-coverage-report
    - if which gcovr >/dev/null ; then cd ${BUILDDIR} ; gcovr --gcov-exclude '.*gtest.*|.*json\.hpp|.*_UnitTests.*|.*test_common\.h|.*BasicLogger\.h' -r .. -s . ; fi
  artifacts:
    paths:
      - ${BUILDDIR}/coverage_report


code-format:
  stage: build
  image: gitlab-registry.cern.ch/lhcb/gitconddb:ubuntu
  dependencies: []
  script:
    - git fetch origin master
    - git diff --name-only --no-renames --diff-filter MA FETCH_HEAD...HEAD | grep -E '\.(h|cpp)$' |
      xargs --no-run-if-empty clang-format-7 -i --style=file || true
    - git diff --name-only --no-renames --diff-filter MA FETCH_HEAD...HEAD | grep -E '\.py$' |
      xargs --no-run-if-empty yapf -i || true
    - "echo \"From: Gitlab CI <noreply@cern.ch>\" > apply-formatting.patch"
    - "echo \"Date: $(date -R)\" >> apply-formatting.patch"
    - "echo \"Subject: [PATCH] Fixed formatting\" >> apply-formatting.patch"
    - echo "" >> apply-formatting.patch
    - echo "patch generated by ${CI_PROJECT_URL}/-/jobs/${CI_JOB_ID}" >> apply-formatting.patch
    - echo "" >> apply-formatting.patch
    - echo "" >> apply-formatting.patch
    - git diff >> apply-formatting.patch
    - git diff --stat --exit-code || (
      echo -e "\n=======================================\n You can fix formatting with:\n\n"
      "  curl ${CI_PROJECT_URL}/-/jobs/${CI_JOB_ID}/artifacts/raw/apply-formatting.patch | git am"
      "\n\n=======================================" ; false
      )
  artifacts:
    paths:
      - apply-formatting.patch
    when: on_failure
    expire_in: 1 day
