# Initial pipeline
trigger:
- azure

- job:
  strategy:
    matrix:
      ubuntu-18.04:
        imageName: 'ubuntu-18.04'
      macos-10.14:
        imageName: 'macos-10.14'
      windows-2019:
        imageName: 'windows-2019'
      windows-2017:
        imageName: 'vs2017-win2016'
  pool:
    vmImage: $(imageName)
  steps:
  - script: brew install boost
    condition: startsWith(variables.imageName,'macos')