# Initial pipeline
trigger:
- azure

jobs:
- job: Hosted
  strategy:
    matrix:
      ubuntu-18.04:
        imageName: 'ubuntu-18.04'
      macos-10.14:
        imageName: 'macos-10.14'
      windows-2019:
        imageName: 'windows-2019'
      windows-2017:
        imageName: 'vs2017-win2016'
  pool:
    vmImage: $(imageName)
  steps:
  - script: brew install boost pkg-config libgit2 fmt
    condition: startsWith(variables.imageName,'macos')
  # FMT is only 4.0 on Ubuntu, so will need to build/cache!
  - script: sudo apt install libgit2-dev
    condition: startsWith(variables.imageName,'ubuntu')
  # Cache will go here...
  - script : |
      git clone https://github.com/fmtlib/fmt.git fmt.git
      cd fmt.git
      git checkout 5.2.1
      cmake -DCMAKE_INSTALL_PREFIX=$(Pipeline.Workspace)/fmt.install -DCMAKE_CXX_STANDARD=17 .
      cmake --build . --target install
    displayName: Build fmt 5.2
    condition: startsWith(variables.imageName,'ubuntu')
  - script: mkdir build
  - script: cmake -DCMAKE_BUILD_TYPE=Debug ..
    displayName: CMake Configure
    workingDirectory: build
  - script: cmake --build . --config Debug
    displayName: CMake Build
    workingDirectory: build
  - script: ctest -VV
    displayName: CTest
    workingDirectory: build
